# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-23 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ajax_django', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WallpaperInfo',
            fields=[
                ('ID', models.CharField(db_index=True, max_length=200, primary_key=True, serialize=False)),
                ('uploadTime', models.DateTimeField()),
                ('downloadpath', models.CharField(max_length=1023)),
                ('index', models.CharField(max_length=4)),
            ],
        ),
    ]
