# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-23 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_django', '0002_wallpaperinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaperinfo',
            name='index',
            field=models.IntegerField(),
        ),
    ]
